#!/bin/sh
ifrm()
{
   :
   #if [ -f "$1" ]; then rm "$1"; fi
}

m4kill()
{
   if [ -f "$1" ]; then
      m4 -DSYS_HOST="$SYS_HOST" -DSYS_OS="$SYS_OS" -DSYS_OSVER="$SYS_OSVER" \
         -DORIG_SYS_LAB="$LAB" -DSYS_TMP_DOMAINNAME="$SYS_TMP_DOMAINNAME" \
         "$1" > "$2"
   fi
   ifrm "$1"
	ifrm "$1~"
}

catkill()
{
   if [ -f "$1" ]; then
      cat "$1" > "$2"
   fi
   ifrm "$1"
   ifrm "$1~"
}

SYS_HOST="`uname -n`"
SYS_OS="`uname -s`"
SYS_OSVER="`uname -r`"
SYS_TMP_DOMAINNAME="`/bin/domainname`"
# non-login interactive shells
m4kill bashrc.m4 "$HOME/.bashrc"
# login interactive shells
m4kill bashrc.m4 "$HOME/.bash_profile"
m4kill zshenv.m4 "$HOME/.zshenv"
m4kill zshrc.m4 "$HOME/.zshrc"
m4kill zlogin.m4 "$HOME/.zlogin"
m4kill zlogout.m4 "$HOME/.zlogout"
m4kill xsession.m4 "$HOME/.xsession"
m4kill xresources.m4 "$HOME/.Xresources"
m4kill xdefaults.m4 "$HOME/.Xdefaults"
m4kill vimrc.m4 "$HOME/.vimrc"
if [ ! -e "$HOME/.wgetrc" ]; then
  m4kill wgetrc.m4 "$HOME/.wgetrc"
fi
catkill screenrc "$HOME/.screenrc"
if [ ! -d "$HOME/etc" ]; then
  mkdir "$HOME/etc"
fi
catkill dalifonts "$HOME/etc/dalifonts"
catkill quotes "$HOME/etc/quotes"
catkill d "$HOME/bin/d"
(cd $HOME/etc ; 2>&1 strfile -r dalifonts dalifonts.dat) > /dev/null
(cd $HOME/etc ; 2>&1 strfile -r quotes quotes.dat) > /dev/null

fvwm2as1()
{
   m4kill fvwm2rc.m4 "$HOME/.fvwmrc"
}

fvwm2()
{
   m4kill fvwm2rc.m4 "$HOME/.fvwm2rc"
}

fvwm()
{
   m4kill fvwmrc.m4 "$HOME/.fvwmrc"
}

case "$LAB" in
   UGCS) fvwm2as1 ;;
   CS) fvwm2; fvwm ;;
   DABNEY) fvwm2; fvwm ;;
   *)
      case "$SYS_HOST" in
         concombre.*|concombre) fvwm2 ;;
         lard.*|lard) fvwm ;;
         *) fvwm2; fvwm ;;
      esac
   ;;
esac
m4kill fvwmrc.m4 "/dev/null"
m4kill fvwm2rc.m4 "/dev/null"

if [ ! -d "$HOME/.ssh" ]; then
   mkdir "$HOME/.ssh"
fi
cp ssh.killagents "$HOME/.ssh/killagents"
ifrm ssh.killagents

crontab crontab
ifrm crontab
ifrm crontab~

if [ ! -d "$HOME/bin" ]; then
  mkdir "$HOME/bin"
fi
m4kill x.m4 "$HOME/bin/x"
chmod a+x "$HOME/bin/x"
catkill genser "$HOME/bin/genser"
chmod a+x "$HOME/bin/genser"

ifrm functions.m4 
ifrm zpath.m4
ifrm init.m4 
ifrm gen~ 
ifrm functions.m4~ 
ifrm init.m4~
ifrm x~
ifrm shells.m4
ifrm shells.m4~
ifrm zpath.m4~
#exec rm gen
