#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "wtanaka.com"
email = "wtanaka@users.noreply.github.com"

[aliases]
bam = ["bookmark", "advance", "main", "--to", "@-"]
gf = ["git", "fetch"]
gfa = ["git", "fetch", "--all-remotes"]
