---
- hosts: all
  roles:
    - wtanaka.autofs
    - wtanaka.bundler
    - wtanaka.chrome
    - wtanaka.darktable
    - { role: wtanaka.docker, docker_users: ['wtanaka'] }
    - wtanaka.dropbox
    - wtanaka.git
    - wtanaka.gnucash
    - wtanaka.keepassx
    - wtanaka.libffi-devel
    - wtanaka.protobuf-compiler
    - wtanaka.proxychains
    - wtanaka.python-dev
    - wtanaka.rawtherapee
    - wtanaka.sshd
    - wtanaka.teamviewer
    - wtanaka.tor
    - wtanaka.vim
    - wtanaka.virtualenv
    - wtanaka.zsh
