---
- hosts: all
  tasks:
    - name: add family group
      group: name=family state=present gid=514
      sudo: yes
    - name: add family group
      user: >
        name=wtanaka
        groups=family
        append=yes
        shell=/bin/zsh
        uid=1026
      sudo: yes
  roles:
    - wtanaka.android-sdk
    - wtanaka.android-studio
    - wtanaka.autofs
    - wtanaka.bundler
    - wtanaka.chrome
    - wtanaka.darktable
    - { role: wtanaka.docker, docker_users: ['wtanaka'] }
    - wtanaka.dropbox
    - wtanaka.exiftool
    - wtanaka.gimp
    - wtanaka.git
    - wtanaka.gitk
    - wtanaka.gnome-raw-thumbnailer
    - wtanaka.gnucash
    - wtanaka.handbrake
    - wtanaka.jq
    - wtanaka.keepassx
    - wtanaka.libffi-devel
    - wtanaka.libssl-devel
    - wtanaka.ngrok
    - wtanaka.oathtool
    - wtanaka.openvpn
    - wtanaka.pbuilder
    - wtanaka.pip
    - wtanaka.protobuf-compiler
    - wtanaka.proxychains
    - wtanaka.python-dev
    - wtanaka.python-tk
    - wtanaka.rawtherapee
    - wtanaka.ruby-dev
    - wtanaka.screen
    - wtanaka.slack
    - wtanaka.sshd
    - wtanaka.teamviewer
    - wtanaka.tor
    - wtanaka.ubuntu-dev-tools
    - wtanaka.vim
    - wtanaka.virtualenv
    - wtanaka.wireshark
    - wtanaka.youtube-dl
    - wtanaka.zsh
