---
- hosts: all
  tasks:
    - name: add family group
      group: name=family state=present gid=514
      sudo: yes
    - name: add family group
      user: >
        name=wtanaka
        groups=family
        append=yes
        shell=/bin/zsh
        uid=1026
      sudo: yes
  roles:
    - wtanaka.autofs
    - wtanaka.bundler
    - wtanaka.chrome
    - wtanaka.darktable
    - { role: wtanaka.docker, docker_users: ['wtanaka'] }
    - wtanaka.dropbox
    - wtanaka.git
    - wtanaka.gnucash
    - wtanaka.keepassx
    - wtanaka.libffi-devel
    - wtanaka.libssl-devel
    - wtanaka.protobuf-compiler
    - wtanaka.proxychains
    - wtanaka.python-dev
    - wtanaka.python-tk
    - wtanaka.rawtherapee
    - wtanaka.sshd
    - wtanaka.teamviewer
    - wtanaka.tor
    - wtanaka.vim
    - wtanaka.virtualenv
    - wtanaka.zsh
