---
- hosts: all
  tasks:
    - name: add family group
      group: name=family state=present gid=514
      sudo: yes
    - name: add family group
      user: >
        name=wtanaka
        groups=family
        append=yes
        shell=/bin/zsh
        uid=1026
      sudo: yes
  roles:
    - wtanaka.alex
    - wtanaka.android-sdk
    - wtanaka.android-studio
    - wtanaka.autofs
    - wtanaka.bundler
    - wtanaka.cabal
    - wtanaka.chrome
    - wtanaka.darktable
    - { role: wtanaka.docker, docker_users: ['wtanaka'] }
    - wtanaka.dropbox
    - wtanaka.exfat
    - wtanaka.exiftool
    - wtanaka.fbreader
    - wtanaka.fdupes
    - role: wtanaka.gcloud-sdk
      additional_package_names:
      - google-cloud-sdk-app-engine-python
    - wtanaka.ghc
    - wtanaka.ghc-mtl
    - wtanaka.gimp
    - wtanaka.git
    - wtanaka.gitk
    - wtanaka.gnome-raw-thumbnailer
    - wtanaka.gnucash
    - wtanaka.graphviz
    - wtanaka.handbrake
    - wtanaka.happy
    - wtanaka.hlint
    - wtanaka.hub
    - wtanaka.inkscape
    - wtanaka.jq
    - wtanaka.keepassx
    - wtanaka.latex
    - wtanaka.libffi-devel
    - wtanaka.libssl-devel
    - wtanaka.maven
    - wtanaka.ngrok
    - wtanaka.numpy
    - wtanaka.oathtool
    - wtanaka.openvpn
    - wtanaka.oracle-java
    - wtanaka.pbuilder
    - wtanaka.pip
    - wtanaka.protobuf-compiler
    - wtanaka.proxychains
    - wtanaka.python-dev
    - wtanaka.python-tk
    - wtanaka.r
    - wtanaka.rawtherapee
    - wtanaka.retext
    - wtanaka.ruby-dev
    - wtanaka.scipy
    - wtanaka.screen
    - wtanaka.slack
    - wtanaka.sqlite
    - wtanaka.sshd
    - wtanaka.teamviewer
    - wtanaka.tig
    - wtanaka.tor
    - wtanaka.ubuntu-dev-tools
    - wtanaka.ufraw
    - wtanaka.vagrant
    - wtanaka.vim
    - wtanaka.virtualbox
    - wtanaka.virtualenv
    - wtanaka.wireshark
    - wtanaka.youtube-dl
    - wtanaka.zsh
