---
- hosts: all
  tasks:
    - name: add family group
      group: name=family state=present gid=514
      sudo: yes
    - name: add family group
      user: >
        name=wtanaka
        groups=family
        append=yes
        shell=/bin/zsh
        uid=1026
      sudo: yes
  roles:
    - wtanaka.alex
    - wtanaka.android_sdk
    - wtanaka.android_studio
    - wtanaka.autofs
    - wtanaka.bluegriffon
    - wtanaka.bundler
    - wtanaka.cabal
    - wtanaka.chrome
    - wtanaka.darktable
    - { role: wtanaka.docker, docker_users: ['wtanaka'] }
    - wtanaka.dropbox
    - wtanaka.exfat
    - wtanaka.exiftool
    - wtanaka.fbreader
    - wtanaka.fdupes
    - role: wtanaka.gcloud_sdk
      additional_package_names:
      - google-cloud-sdk-app-engine-python
      - google-cloud-sdk-app-engine-java
    - wtanaka.gephi
    - wtanaka.ghc
    - wtanaka.ghc_mtl
    - wtanaka.gimp
    - wtanaka.git
    - wtanaka.gitk
    - wtanaka.gnome-raw-thumbnailer
    - wtanaka.gnucash
    - wtanaka.graphviz
    - wtanaka.handbrake
    - wtanaka.happy
    - wtanaka.hlint
    - wtanaka.hub
    - wtanaka.inkscape
    - wtanaka.intellij
    - wtanaka.jq
    - wtanaka.keepassx
    - wtanaka.latex
    - wtanaka.libffi_devel
    - wtanaka.libssl_devel
    - wtanaka.maven
    - wtanaka.ngrok
    - wtanaka.numpy
    - wtanaka.oathtool
    - wtanaka.openvpn
    - wtanaka.oracle-java
    - wtanaka.pbuilder
    - wtanaka.pip
    - wtanaka.pngcrush
    - wtanaka.pngnq
    - wtanaka.protobuf-compiler
    - wtanaka.proxychains
    - wtanaka.python_dev
    - wtanaka.python_tk
    - wtanaka.qemu
    - wtanaka.r
    - wtanaka.rawtherapee
    - wtanaka.retext
    - wtanaka.ruby_dev
    - wtanaka.scipy
    - wtanaka.screen
    - wtanaka.screenruler
    - wtanaka.slack
    - wtanaka.sqlite
    - wtanaka.sshd
    - wtanaka.teamviewer
    - wtanaka.tig
    - wtanaka.tor
    - wtanaka.ubuntu_dev_tools
    - wtanaka.ufraw
    - wtanaka.vagrant
    - wtanaka.vim
    - wtanaka.virtualbox
    - wtanaka.virtualenv
    - wtanaka.whois
    - wtanaka.wireshark
    - wtanaka.youtube_dl
    - wtanaka.zsh
