# Switch prefix key from C-b to C-]
set -g prefix C-]
unbind C-b
bind C-] send-prefix

# C-] C-] switches to the last active window like in screen
bind-key C-] last-window
# Allow sending a literal C-] with C-] ]
bind-key ] send-keys C-]

# Turn off the status bar to reclaim a line
set -g status off
# Increase the time status messages are displayed to 1 second
set -g display-time 1000
# Attempt to set the client terminal title
set -g set-titles on
# Put the user-set title first
set -g set-titles-string "\"#T\" - #S:#I:#W #{session_alerts}"

# "0" is all the way on the right side of the keyboard.
# Unfortunately, this doesnt change the numbering in the choose-window
# list.
set -g base-index 1

# Make typing deterministic by turning off escape-time
set -s escape-time 0

# Allow windows to get automatically resized larger instead of only
# just smaller
set-window-option -g aggressive-resize on

# Use vi keys
set-window-option -g mode-keys vi
