#!/bin/sh
# Shellfun http://shellfun.sf.net/
# 
# Copyright (C) 2007-2014 Wesley Tanaka http://wtanaka.com/
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Command line script to urlencode a string using sed
(if [ -z "$*" ]; then
   cat
else
   echo -n "$*"
fi) | sed \
   -e 's/\%/%25/g' \
   -e 's/\+/%2B/g' \
   -e 's/ /+/g' \
   -e 's/\!/%21/g' \
   -e 's/\"/%22/g' \
   -e 's/\#/%23/g' \
   -e 's/\$/%24/g' \
   -e 's/\&/%26/g' \
   -e 's/'\''/%27/g' \
   -e 's/(/%28/g' \
   -e 's/)/%29/g' \
   -e 's/\*/%2A/g' \
   -e 's/\,/%2C/g' \
   -e 's/\//%2F/g' \
   -e 's/\:/%3A/g' \
   -e 's/\;/%3B/g' \
   -e 's/</%3C/g' \
   -e 's/\=/%3D/g' \
   -e 's/>/%3E/g' \
   -e 's/\?/%3F/g' \
   -e 's/\@/%40/g' \
   -e 's/\[/%5B/g' \
   -e 's/\\/%5C/g' \
   -e 's/\]/%5D/g' \
   -e 's/\^/%5E/g' \
   -e 's/`/%60/g' \
   -e 's/{/%7B/g' \
   -e 's/|/%7C/g' \
   -e 's/}/%7D/g' \

#DEL                         7F    
#00    NUL ’\0’                    
#01    SOH (start of heading)      
#02    STX (start of text)         
#03    ETX (end of text)           
#04    EOT (end of transmission)   
#05    ENQ (enquiry)               
#06    ACK (acknowledge)           
#07    BEL ’\a’ (bell)             
#08    BS  ’\b’ (backspace)        
#09    HT  ’\t’ (horizontal tab)   
#0A    LF  ’\n’ (new line)         
#0B    VT  ’\v’ (vertical tab)     
#0C    FF  ’\f’ (form feed)        
#0D    CR  ’\r’ (carriage ret)     
#0E    SO  (shift out)             
#0F    SI  (shift in)              
#10    DLE (data link escape)      
#11    DC1 (device control 1)      
#12    DC2 (device control 2)      
#13    DC3 (device control 3)      
#14    DC4 (device control 4)      
#15    NAK (negative ack.)         
#16    SYN (synchronous idle)      
#17    ETB (end of trans. blk)     
#18    CAN (cancel)                
#19    EM  (end of medium)         
#1A    SUB (substitute)            
#1B    ESC (escape)                
#1C    FS  (file separator)        
#1D    GS  (group separator)       
#1E    RS  (record separator)      
#1F    US  (unit separator)        
